[package]
name = "plist"
version = "0.0.16"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Very much a work in progress."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://docs.rs/plist/0.0.16/plist/"
keywords = ["plist", "parser"]
build = "build.rs"

[features]
serde_tests = ["serde_codegen"]

[dependencies]
rustc-serialize = "0.3.19"
xml-rs = "0.3.4"
byteorder = "0.5.3"
chrono = "0.2.22"
serde = "0.7.10"

[build-dependencies]
serde_codegen = { version = "0.7.10", optional = true }
