[package]
name = "plist"
version = "0.0.11"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Very much a work in progress."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://ebarnard.github.io/rust-plist/"
keywords = ["plist", "parser"]
build = "build.rs"

[features]
serde_tests = ["serde_codegen", "syntex"]

[dependencies]
rustc-serialize = "0.3.16"
xml-rs = "0.2.2"
byteorder = "0.4.2"
chrono = "0.2.17"
serde = "0.6.7"

[build-dependencies]
serde_codegen = { version = "0.6.7", optional = true }
syntex = { version = "0.24.0", optional = true }
