[package]
name = "plist"
version = "0.0.2"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Very much a work in progress."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist"

[dependencies]
rustc-serialize = "0.3.15"
xml-rs = "0.1.25"