[package]
name = "plist"
version = "0.0.10"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Very much a work in progress."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://ebarnard.github.io/rust-plist/"
keywords = ["plist", "parser"]

[dependencies]
rustc-serialize = "0.3.16"
xml-rs = "0.2.2"
byteorder = "0.4.2"
chrono = "0.2.17"
